-- DATA-02: deferrable unique constraint on cities (user_id, order_index).
-- This file is hand-authored, NOT generated by drizzle-kit. It is owned
-- by REQUIREMENTS.md DATA-02 and referenced by schema.ts's top-of-file
-- ownership notice. Do not delete this file when running `bun run db:generate`
-- in future phases; Drizzle Kit's diff sees nothing in schema.ts and will
-- not touch it.
--
-- Why DEFERRABLE: Phase 5's PATCH /api/cities/reorder swaps order_index
-- values across multiple rows in one transaction. Without DEFERRABLE,
-- Postgres checks uniqueness after each UPDATE statement and rejects
-- intermediate states (e.g., temporarily two rows at order_index=2). With
-- DEFERRABLE INITIALLY DEFERRED, the check is deferred until COMMIT, so
-- the final ordering is what gets validated.

ALTER TABLE cities
  ADD CONSTRAINT cities_user_id_order_index_unique
  UNIQUE (user_id, order_index)
  DEFERRABLE INITIALLY DEFERRED;
